version: "3.8"

services:

  db_projeto06:
    container_name: database06
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projeto06_database
    volumes:
      - pgdata:/data/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=1234

  app:
    build: .
    container_name: projeto06
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db_projeto06
      - redis
    depends_on:
      - db_projeto06
      - redis

volumes:
  pgdata:
    driver: local
